logging:
  level:
    root: INFO
management:
  endpoints:
    enabled-by-default: true
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: false
    defaults:
      enabled: true
    diskspace:
      enabled: true
    livenessstate:
      enabled: true
    